title: Page

buttons:
  - preview
  - settings
  - content-translator
  - languages
  - status

tabs:
  objectFields:
    label: Object & Structure Fields
    columns:
      - width: 2/3
        fields:
          table:
            label: Table
            type: table
      - width: 1/3
        sections:
          contentTranslator02:
            type: content-translator
            label: Content Translator
            title: true
            # slug: true
