minimumReleaseAgeExcludePrune: true
minimumReleaseAgeExclude:
  - kirby-types@1.8.1
  - kirbyuse@1.4.1
  - utilful@3.5.1
  - '@kirby-tools/licensing@0.9.0'

trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
  - semver@6.3.1
  - vite@6.3.7

shellEmulator: true
allowBuilds:
  "@parcel/watcher": true
  esbuild: true
