minimumReleaseAgeExcludePrune: true
minimumReleaseAgeExclude:
  - kirby-types@1.6.2
  - kirbyuse@1.4.1

trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
  - semver@6.3.1
  - vite@6.3.7

shellEmulator: true
allowBuilds:
  "@parcel/watcher": true
  esbuild: true
