title: Playground

buttons:
  preview: true
  content-translator:
    label: Translate
    importFrom: all
    batch: false
    title: true
    slug: false
  languages: true

sections:
  pages:
    type: pages
